server:
  port: 9003
spring:
  application:
    name: org-service  #服务名，将注册到eureka注册中心
    
eureka:
  instance: 
    status-page-url-path: ${management.context-path}/info
    health-check-url-path: ${management.context-path}/health
  client:
    service-url:
      defaultZone: http://root:123456@localhost:8761/register-center/eureka/  #注册地址，eureka服务地址      
      
      